#!/bin/bash

set -euo pipefail

# Requires KVM
./check_package "kvm" "vagrant"

# Vagrant
wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
apt update && apt install vagrant

# Enable "universe" source code repos
cp /etc/apt/sources.list /etc/apt/sources.list."$(date +"%F")"
sed -i -e '/^# deb-src.*universe$/s/# //g' /etc/apt/sources.list
apt-get -y update

# Plugin prerequisites
apt-get -y install nfs-kernel-server
systemctl enable --now nfs-server
apt-get -y build-dep vagrant ruby-libvirt
apt-get -y install ebtables dnsmasq-base
apt-get -y install libxslt-dev libxml2-dev libvirt-dev zlib1g-dev ruby-dev

# Libvirt plugin
vagrant plugin install vagrant-libvirt
